"""add id in invitation

Revision ID: 00ceb8a6d037
Revises: a4ef5182305c
Create Date: 2017-02-01 18:27:56.015323

"""

# revision identifiers, used by Alembic.
revision = '00ceb8a6d037'
down_revision = 'a4ef5182305c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_invitation_user', 'users', ['invitee_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invitation_user', type_='foreignkey')
        batch_op.drop_column('invitee_id')

    ### end Alembic commands ###
