"""remove review delegation

Revision ID: 0c24adbbb3d8
Revises: e30377ad6b16
Create Date: 2017-03-06 17:58:22.839019

"""

# revision identifiers, used by Alembic.
revision = '0c24adbbb3d8'
down_revision = 'e30377ad6b16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delegate_reviewers')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_conference_id'), ['conference_id'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_conference_id'))

    op.create_table('delegate_reviewers',
    sa.Column('delegator_id', sa.INTEGER(), nullable=False),
    sa.Column('delegatee_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('paper_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['delegatee_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['delegator_id'], [u'users.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], [u'papers.id'], ),
    sa.PrimaryKeyConstraint('delegator_id', 'paper_id')
    )
    ### end Alembic commands ###
