"""update sessions

Revision ID: 1234aba3e283
Revises: 19325c6852ae
Create Date: 2017-09-27 12:36:42.364676

"""

# revision identifiers, used by Alembic.
revision = '1234aba3e283'
down_revision = '19325c6852ae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('end_time',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('start_time',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_sessions_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_column('date')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_sessions_timestamp'))
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)
        batch_op.drop_column('timestamp')

    ### end Alembic commands ###
