"""add currency in product

Revision ID: 1426a81c6079
Revises: 37589c1a2322
Create Date: 2018-05-21 10:58:50.835479

"""

# revision identifiers, used by Alembic.
revision = '1426a81c6079'
down_revision = '37589c1a2322'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('currency')

    ### end Alembic commands ###
