"""add notification

Revision ID: 14d9e98f7176
Revises: 325f35d1ad82
Create Date: 2017-08-17 14:48:38.945601

"""

# revision identifiers, used by Alembic.
revision = '14d9e98f7176'
down_revision = '325f35d1ad82'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('display', JsonObject, nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_seen'), ['seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_timestamp'), ['timestamp'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_timestamp'))
        batch_op.drop_index(batch_op.f('ix_notifications_seen'))
        batch_op.drop_index(batch_op.f('ix_notifications_receiver_id'))

    op.drop_table('notifications')
    ### end Alembic commands ###
