"""support promo code and merchandise

Revision ID: 156042f3b6f8
Revises: 2fbf3151ccc1
Create Date: 2016-06-22 12:04:10.425630

"""

# revision identifiers, used by Alembic.
revision = '156042f3b6f8'
down_revision = '2fbf3151ccc1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    import os
    conf_config = os.environ.get('CONF_CONFIG') or 'default'
    if conf_config == 'production':  # only run this for MySQL
        op.execute('SET foreign_key_checks = 0')
        
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('require', sa.Boolean(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_timestamp'), ['timestamp'], unique=False)

    op.create_table('product_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.String(length=16), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=32), nullable=True),
    sa.Column('option_price', sa.Float(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_options_default'), ['default'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_options_timestamp'), ['timestamp'], unique=False)

    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('usage', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promo_codes_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table(u'ticket_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_promo_code_ticket_transaction', 'promo_codes', ['promo_code_id'], ['id'])

    op.create_table('product_option_sale',
    sa.Column('product_option_id', sa.Integer(), nullable=False),
    sa.Column('ticket_transaction_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_option_id'], ['product_options.id'], ),
    sa.ForeignKeyConstraint(['ticket_transaction_id'], ['ticket_transactions.id'], ),
    sa.PrimaryKeyConstraint('product_option_id', 'ticket_transaction_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'ticket_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_promo_code_ticket_transaction', type_='foreignkey')
        batch_op.drop_column('promo_code_id')

    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promo_codes_timestamp'))

    op.drop_table('promo_codes')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_timestamp'))

    op.drop_table('products')
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_options_timestamp'))
        batch_op.drop_index(batch_op.f('ix_product_options_default'))

    op.drop_table('product_options')
    op.drop_table('product_option_sale')
    ### end Alembic commands ###
