"""add payout

Revision ID: 157de9c4480d
Revises: 1d067cc24a5a
Create Date: 2016-08-09 17:35:10.570172

"""

# revision identifiers, used by Alembic.
revision = '157de9c4480d'
down_revision = '1d067cc24a5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=64), nullable=True),
    sa.Column('street_1', sa.String(length=128), nullable=True),
    sa.Column('street_2', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('zipcode', sa.String(length=8), nullable=True),
    sa.Column('payment_method', sa.String(length=16), nullable=True),
    sa.Column('bank_name', sa.String(length=64), nullable=True),
    sa.Column('account_type', sa.String(length=8), nullable=True),
    sa.Column('routing_number', sa.String(length=9), nullable=True),
    sa.Column('account_number', sa.String(length=32), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('update_timestamp', sa.DateTime(), nullable=True),
    sa.Column('payment_finish_timestamp', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(u'form_configuration', schema=None) as batch_op:
        batch_op.drop_column('payout_scheme')

    with op.batch_alter_table(u'registrations', schema=None) as batch_op:
        batch_op.drop_column('payout')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout', sa.BLOB(), nullable=True))

    with op.batch_alter_table(u'form_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_scheme', sa.BLOB(), nullable=True))

    op.drop_table('payouts')
    ### end Alembic commands ###
