"""add review_questions and review_answers

Revision ID: 1598d38945bb
Revises: 1d5e008931f0
Create Date: 2016-05-27 10:53:05.371597

"""

# revision identifiers, used by Alembic.
revision = '1598d38945bb'
down_revision = '1d5e008931f0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('review_questions', sa.PickleType(), nullable=True))
    op.add_column('reviews', sa.Column('review_answer', sa.PickleType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'review_answer')
    op.drop_column('conferences', 'review_questions')
    ### end Alembic commands ###