"""add primary id in users

Revision ID: 18f1e17a6839
Revises: 1426a81c6079
Create Date: 2018-05-22 11:10:19.866328

"""

# revision identifiers, used by Alembic.
revision = '18f1e17a6839'
down_revision = '1426a81c6079'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('users_fk_users', 'users', ['primary_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_fk_users', type_='foreignkey')
        batch_op.drop_column('primary_id')

    ### end Alembic commands ###
