"""add proceeding_included in paper

Revision ID: 19325c6852ae
Revises: eef2781c83d3
Create Date: 2017-09-18 17:21:48.087979

"""

# revision identifiers, used by Alembic.
revision = '19325c6852ae'
down_revision = 'eef2781c83d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proceeding_included', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('proceeding_included')

    ### end Alembic commands ###
