"""add track_id in invitation

Revision ID: 1d067cc24a5a
Revises: 4c4af1936ba4
Create Date: 2016-08-02 17:42:13.459631

"""

# revision identifiers, used by Alembic.
revision = '1d067cc24a5a'
down_revision = '4c4af1936ba4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_track+invitation', 'tracks', ['track_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_track+invitation', type_='foreignkey')
        batch_op.drop_column('track_id')

    ### end Alembic commands ###
