"""update paper and userdoc

Revision ID: 24138af3443
Revises: 19dc96f521e2
Create Date: 2016-11-17 16:58:30.771120

"""

# revision identifiers, used by Alembic.
revision = '24138af3443'
down_revision = 'fc3420d65a2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_paper_userDoc', 'papers', ['paper_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('paper_id')

    ### end Alembic commands ###
