"""empty message

Revision ID: 265fd0240ff4
Revises: 8a60c5a5d602
Create Date: 2017-12-07 00:45:33.205831

"""

# revision identifiers, used by Alembic.
revision = '265fd0240ff4'
down_revision = '8a60c5a5d602'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('commenter_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['commenter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_comments_timestamp'), ['timestamp'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_comments_timestamp'))

    op.drop_table('review_comments')
    ### end Alembic commands ###
