"""update TicketTransaction

Revision ID: 2fbf3151ccc1
Revises: 1598d38945bb
Create Date: 2016-06-08 15:00:44.118389

"""

# revision identifiers, used by Alembic.
revision = '2fbf3151ccc1'
down_revision = '1598d38945bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_city', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('billing_state', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('billing_street', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('billing_zipcode', sa.String(length=8), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.drop_column('billing_street')
        batch_op.drop_column('billing_state')
        batch_op.drop_column('billing_city')
        batch_op.drop_column('billing_zipcode')

    ### end Alembic commands ###
