"""add type in eventlog

Revision ID: 325f35d1ad82
Revises: dd48947ccf75
Create Date: 2017-08-08 12:03:39.938581

"""

# revision identifiers, used by Alembic.
revision = '325f35d1ad82'
down_revision = 'dd48947ccf75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=64), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_column('type')

    ### end Alembic commands ###
