"""add profile

Revision ID: 330a14bde8ef
Revises: 8534f1bec123
Create Date: 2017-10-10 12:29:15.168309

"""

# revision identifiers, used by Alembic.
revision = '330a14bde8ef'
down_revision = '8534f1bec123'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile', JsonObject, nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_user', schema=None) as batch_op:
        batch_op.drop_column('profile')

    ### end Alembic commands ###
