"""add net and balance_transaction_id

Revision ID: 359785c37503
Revises: 93345d70092d
Create Date: 2018-07-22 16:45:32.606390

"""

# revision identifiers, used by Alembic.
revision = '359785c37503'
down_revision = '93345d70092d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_transaction_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('net', sa.Float(), nullable=True))
        batch_op.alter_column('payer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_transaction_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('net', sa.Float(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.drop_column('net')
        batch_op.drop_column('balance_transaction_id')

    with op.batch_alter_table('conference_transactions', schema=None) as batch_op:
        batch_op.alter_column('payer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('net')
        batch_op.drop_column('balance_transaction_id')

    ### end Alembic commands ###
