"""update promo code

Revision ID: 37589c1a2322
Revises: 443a86885f9b
Create Date: 2018-05-18 12:06:10.086733

"""

# revision identifiers, used by Alembic.
revision = '37589c1a2322'
down_revision = '443a86885f9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promo_codes', schema=None) as batch_op:
        batch_op.drop_column('currency')

    ### end Alembic commands ###
