"""update configuration in conference

Revision ID: 37f4373c81c
Revises: 157de9c4480d
Create Date: 2016-08-17 15:32:31.032213

"""

# revision identifiers, used by Alembic.
revision = '37f4373c81c'
down_revision = '157de9c4480d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configuration', sa.PickleType(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('configuration')

    ### end Alembic commands ###
