"""empty message

Revision ID: 392b5d658dcf
Revises: 485440dc4ad
Create Date: 2016-10-26 02:46:43.934601

"""

# revision identifiers, used by Alembic.
revision = '392b5d658dcf'
down_revision = '485440dc4ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_review_questions', sa.PickleType(), nullable=True))

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_private_question', sa.PickleType(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('deleted_private_question')

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('deleted_review_questions')

    ### end Alembic commands ###
