"""drop private question

Revision ID: 3b20d207b79a
Revises: 392b5d658dcf
Create Date: 2016-10-31 00:28:23.100604

"""

# revision identifiers, used by Alembic.
revision = '3b20d207b79a'
down_revision = '392b5d658dcf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('deleted_review_questions')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('deleted_private_question')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_private_question', sa.BLOB(), nullable=True))

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_review_questions', sa.BLOB(), nullable=True))

    ### end Alembic commands ###
