"""add num_of_sold in product option

Revision ID: 41d66b4678f2
Revises: 156042f3b6f8
Create Date: 2016-06-24 16:21:59.262812

"""

# revision identifiers, used by Alembic.
revision = '41d66b4678f2'
down_revision = '156042f3b6f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conferences_short_name'), ['short_name'], unique=False)

    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_sold', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_options', schema=None) as batch_op:
        batch_op.drop_column('number_of_sold')

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conferences_short_name'))

    ### end Alembic commands ###
