"""add status, timestamp, payer id  in conference transaction

Revision ID: 443a86885f9b
Revises: dde53052da30
Create Date: 2018-04-29 10:26:03.255059

"""

# revision identifiers, used by Alembic.
revision = '443a86885f9b'
down_revision = 'dde53052da30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charge_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('refund_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('fk_user_conference_transaction', 'users', ['payer_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_conference_transaction', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('refund_timestamp')
        batch_op.drop_column('payer_id')
        batch_op.drop_column('charge_timestamp')

    ### end Alembic commands ###
