"""add associated emails and paper biddings

Revision ID: 4755a0f19529
Revises: 67005ff00719
Create Date: 2017-03-15 17:43:01.176829

"""

# revision identifiers, used by Alembic.
revision = '4755a0f19529'
down_revision = '67005ff00719'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associated_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('associated_emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_associated_emails_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_associated_emails_user_id'), ['user_id'], unique=False)

    op.create_table('paper_pc_bidding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_pc_bidding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_pc_bidding_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_pc_bidding_user_id'), ['user_id'], unique=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_pc_bidding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_pc_bidding_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_pc_bidding_paper_id'))

    op.drop_table('paper_pc_bidding')
    with op.batch_alter_table('associated_emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_associated_emails_user_id'))
        batch_op.drop_index(batch_op.f('ix_associated_emails_email'))

    op.drop_table('associated_emails')
    ### end Alembic commands ###
