"""add label in paper

Revision ID: 4b6909ef6e08
Revises: 330a14bde8ef
Create Date: 2017-10-13 11:24:19.017143

"""

# revision identifiers, used by Alembic.
revision = '4b6909ef6e08'
down_revision = '330a14bde8ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('label')

    ### end Alembic commands ###
