"""update invitation

Revision ID: 4c4af1936ba4
Revises: 2b71bb537ba8
Create Date: 2016-07-30 20:28:08.358567

"""

# revision identifiers, used by Alembic.
revision = '4c4af1936ba4'
down_revision = '2b71bb537ba8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conference_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_conference_invitation', 'conferences', ['conference_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conference_invitation', type_='foreignkey')
        batch_op.drop_column('conference_id')

    ### end Alembic commands ###
