"""add paper_type

Revision ID: 4dd4a1538dc5
Revises: 8c4c4387f71f
Create Date: 2017-03-09 23:04:26.973761

"""

# revision identifiers, used by Alembic.
revision = '4dd4a1538dc5'
down_revision = '8c4c4387f71f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_type', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('submission_type')

    ### end Alembic commands ###
