"""add timezone in conference

Revision ID: 4ed839b92a24
Revises: 4f4c4709b4e8
Create Date: 2016-07-26 02:04:13.127028

"""

# revision identifiers, used by Alembic.
revision = '4ed839b92a24'
down_revision = '4f4c4709b4e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=33), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    ### end Alembic commands ###
