"""add submission deadline

Revision ID: 4f4c4709b4e8
Revises: 3b0f0ad0475e
Create Date: 2016-07-22 23:22:49.999036

"""

# revision identifiers, used by Alembic.
revision = '4f4c4709b4e8'
down_revision = '3b0f0ad0475e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_deadline', sa.Date(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('submission_deadline')

    ### end Alembic commands ###
