"""add configuration in track

Revision ID: 506419d6901a
Revises: eaea5a74a92d
Create Date: 2017-02-04 21:11:44.742519

"""

# revision identifiers, used by Alembic.
revision = '506419d6901a'
down_revision = 'eaea5a74a92d'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('configuration', JsonObject, nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('configuration')

    ### end Alembic commands ###
