"""add review delegate

Revision ID: 5102b2f9d9b7
Revises: 37f4373c81c
Create Date: 2016-09-08 15:22:10.781150

"""

# revision identifiers, used by Alembic.
revision = '5102b2f9d9b7'
down_revision = '37f4373c81c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delegate_reviewers',
    sa.Column('delegator_id', sa.Integer(), nullable=False),
    sa.Column('delegatee_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delegatee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['delegator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('delegator_id', 'paper_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delegate_reviewers')
    ### end Alembic commands ###
