"""Add UserDoc status

Revision ID: 54288858e30f
Revises: b372f99f3d6c
Create Date: 2018-02-23 05:07:11.940798

"""

# revision identifiers, used by Alembic.
revision = '54288858e30f'
down_revision = 'b372f99f3d6c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_documents', schema=None) as batch_op:
        batch_op.drop_column('status')

    ### end Alembic commands ###
