"""add balance_transaction_amount

Revision ID: 60b4b982a160
Revises: 98a84ce9f11c
Create Date: 2018-07-24 11:17:41.817543

"""

# revision identifiers, used by Alembic.
revision = '60b4b982a160'
down_revision = '98a84ce9f11c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_transaction_amount', sa.Float(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.drop_column('balance_transaction_amount')

    ### end Alembic commands ###
