"""add manu in join track

Revision ID: 613bb1cf9f38
Revises: 515c73f0bce4
Create Date: 2017-10-24 16:44:52.786368

"""

# revision identifiers, used by Alembic.
revision = '613bb1cf9f38'
down_revision = '515c73f0bce4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_added', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_user', schema=None) as batch_op:
        batch_op.drop_column('manual_added')

    ### end Alembic commands ###
