"""add ticket price clas

Revision ID: 6a297f9496de
Revises: 6cc66feadd69
Create Date: 2018-01-18 02:06:59.083006

"""

# revision identifiers, used by Alembic.
revision = '6a297f9496de'
down_revision = '6cc66feadd69'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_prices')
    ### end Alembic commands ###
