"""add favsession

Revision ID: 6cc66feadd69
Revises: cd568e6ac99a
Create Date: 2018-01-09 22:06:18.086806

"""

# revision identifiers, used by Alembic.
revision = '6cc66feadd69'
down_revision = 'cd568e6ac99a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'session_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav_sessions')
    ### end Alembic commands ###
