"""add more fk in eventlog

Revision ID: 75b82a05837e
Revises: 9ac57fe9ed79
Create Date: 2017-09-07 18:25:42.129725

"""

# revision identifiers, used by Alembic.
revision = '75b82a05837e'
down_revision = '9ac57fe9ed79'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delegate_reviewers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conference_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_delegation_review_conference', 'conferences', ['conference_id'], ['id'])

    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paper_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_paper_event_log', 'papers', ['paper_id'], ['id'])
        batch_op.create_foreign_key('fk_review_event_log', 'reviews', ['review_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_paper_event_log', type_='foreignkey')
        batch_op.drop_constraint('fk_review_event_log', type_='foreignkey')
        batch_op.drop_column('review_id')
        batch_op.drop_column('paper_id')

    with op.batch_alter_table('delegate_reviewers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_delegation_review_conference', type_='foreignkey')
        batch_op.drop_column('conference_id')

    ### end Alembic commands ###
