"""add status in session

Revision ID: 8534f1bec123
Revises: 1234aba3e283
Create Date: 2017-09-29 14:38:37.503819

"""

# revision identifiers, used by Alembic.
revision = '8534f1bec123'
down_revision = '1234aba3e283'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('status')

    ### end Alembic commands ###
