"""add conference payment

Revision ID: 8a60c5a5d602
Revises: 613bb1cf9f38
Create Date: 2017-11-08 14:19:28.375735

"""

# revision identifiers, used by Alembic.
revision = '8a60c5a5d602'
down_revision = '613bb1cf9f38'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_addons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('num_sold', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('card_info', JsonObject, nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('charged', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference_promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('usage', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conference_promo_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conference_promo_codes_timestamp'), ['timestamp'], unique=False)

    op.create_table('conference_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_payment_id', sa.Integer(), nullable=True),
    sa.Column('charge_id', sa.Text(), nullable=True),
    sa.Column('refund_id', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conference_payment_id'], ['conference_payments.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['conference_promo_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_addon',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('addon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['conference_addons.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['conference_transactions.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'addon_id')
    )
    with op.batch_alter_table(u'conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=32), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'conferences', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.drop_table('transaction_addon')
    op.drop_table('conference_transactions')
    with op.batch_alter_table('conference_promo_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conference_promo_codes_timestamp'))

    op.drop_table('conference_promo_codes')
    op.drop_table('conference_payments')
    op.drop_table('conference_addons')
    ### end Alembic commands ###
