"""update email template

Revision ID: 8c4c4387f71f
Revises: 4755a0f19529
Create Date: 2017-03-19 18:21:27.644150

"""

# revision identifiers, used by Alembic.
revision = '8c4c4387f71f'
down_revision = '4755a0f19529'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_email_template_user', 'users', ['user_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_email_template_user', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamp')

    ### end Alembic commands ###
