"""add number of sold in price

Revision ID: 93345d70092d
Revises: 18f1e17a6839
Create Date: 2018-07-16 20:17:17.258417

"""

# revision identifiers, used by Alembic.
revision = '93345d70092d'
down_revision = '18f1e17a6839'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_sold', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_prices', schema=None) as batch_op:
        batch_op.drop_column('number_of_sold')

    ### end Alembic commands ###
