"""add browser in request log

Revision ID: 9ac57fe9ed79
Revises: d64def604006
Create Date: 2017-09-02 21:14:21.063571

"""

# revision identifiers, used by Alembic.
revision = '9ac57fe9ed79'
down_revision = 'd64def604006'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser', sa.String(length=32), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_logs', schema=None) as batch_op:
        batch_op.drop_column('browser')

    ### end Alembic commands ###
