"""update track

Revision ID: a4ef5182305c
Revises: 10ef2eaf5333
Create Date: 2017-01-10 21:16:07.589008

"""

# revision identifiers, used by Alembic.
revision = 'a4ef5182305c'
down_revision = '10ef2eaf5333'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_track_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_track_track', 'tracks', ['parent_track_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_track_track', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('parent_track_id')

    ### end Alembic commands ###
