"""add request log

Revision ID: a7ef1f4d005a
Revises: ab9c1f3cd1f6
Create Date: 2017-08-31 21:04:13.590410

"""

# revision identifiers, used by Alembic.
revision = 'a7ef1f4d005a'
down_revision = 'ab9c1f3cd1f6'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject
import app

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', app.utils.guid.GUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('real_user_id', sa.Integer(), nullable=True),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('is_xhr', sa.Boolean(), nullable=True),
    sa.Column('blueprint_name', sa.String(length=32), nullable=True),
    sa.Column('function_name', sa.String(length=128), nullable=True),
    sa.Column('view_args', JsonObject, nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=256), nullable=True),
    sa.Column('remote_ip', sa.String(length=256), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('http_method', sa.String(length=16), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('http_version', sa.String(length=32), nullable=True),
    sa.Column('interaction_milli', sa.Integer(), nullable=True),
    sa.Column('query_string', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['real_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_logs')
    ### end Alembic commands ###
