"""convert attentee_info to json

Revision ID: a9758ba3a4db
Revises: 24138af3443
Create Date: 2016-11-30 16:03:11.514605

"""

# revision identifiers, used by Alembic.
revision = 'a9758ba3a4db'
down_revision = '24138af3443'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.alter_column('attendee_info',
               existing_type=sa.BLOB(),
               type_=JsonObject,
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.alter_column('attendee_info',
               existing_type=JsonObject,
               type_=sa.BLOB(),
               existing_nullable=True)

    ### end Alembic commands ###
