"""add review preference

Revision ID: ab9c1f3cd1f6
Revises: 14d9e98f7176
Create Date: 2017-08-30 14:46:13.102589

"""

# revision identifiers, used by Alembic.
revision = 'ab9c1f3cd1f6'
down_revision = '14d9e98f7176'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('conference_id', sa.Integer(), nullable=True),
    sa.Column('assigned_reviews_num', sa.Integer(), nullable=True),
    sa.Column('assigned_reviews_max', sa.Integer(), nullable=True),
    sa.Column('preferred_keywords', sa.Text(), nullable=True),
    sa.Column('rejected_keywords', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table(u'associated_emails', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table(u'authors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table(u'conferences', schema=None) as batch_op:
        batch_op.alter_column('contact_email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table(u'invitations', schema=None) as batch_op:
        batch_op.alter_column('invitee_email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table(u'payouts', schema=None) as batch_op:
        batch_op.alter_column('account_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table(u'users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table(u'payouts', schema=None) as batch_op:
        batch_op.alter_column('account_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table(u'invitations', schema=None) as batch_op:
        batch_op.alter_column('invitee_email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table(u'conferences', schema=None) as batch_op:
        batch_op.alter_column('contact_email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table(u'authors', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table(u'associated_emails', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    op.drop_table('review_preferences')
    ### end Alembic commands ###
