"""update ticket transactions

Revision ID: b372f99f3d6c
Revises: 6a297f9496de
Create Date: 2018-02-08 16:24:17.490998

"""

# revision identifiers, used by Alembic.
revision = 'b372f99f3d6c'
down_revision = '6a297f9496de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_price_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_ticket_sale_ticket_price', 'ticket_prices', ['ticket_price_id'], ['id'])

    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8)))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_transactions', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('ticket_sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_sale_ticket_price', type_='foreignkey')
        batch_op.drop_column('ticket_price_id')

    ### end Alembic commands ###
