"""add invitee first name and last name in Invitation

Revision ID: cc8a04bf1a9e
Revises: 506419d6901a
Create Date: 2017-02-06 14:46:04.982255

"""

# revision identifiers, used by Alembic.
revision = 'cc8a04bf1a9e'
down_revision = '506419d6901a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitee_first_name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('invitee_last_name', sa.String(length=64), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_column('invitee_last_name')
        batch_op.drop_column('invitee_first_name')

    ### end Alembic commands ###
