"""empty message

Revision ID: cd568e6ac99a
Revises: 265fd0240ff4
Create Date: 2017-12-07 01:24:53.059131

"""

# revision identifiers, used by Alembic.
revision = 'cd568e6ac99a'
down_revision = '265fd0240ff4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))
        batch_op.drop_column('comments')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.TEXT(), nullable=True))
        batch_op.drop_column('text')

    ### end Alembic commands ###
