"""add conference id in review

Revision ID: d64def604006
Revises: a7ef1f4d005a
Create Date: 2017-09-01 20:44:15.396434

"""

# revision identifiers, used by Alembic.
revision = 'd64def604006'
down_revision = 'a7ef1f4d005a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conference_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_review_conference', 'conferences', ['conference_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_conference', type_='foreignkey')
        batch_op.drop_column('conference_id')

    ### end Alembic commands ###
