"""add publish to schedule

Revision ID: dd48947ccf75
Revises: e2cfd701b7ac
Create Date: 2017-07-24 15:26:58.144810

"""

# revision identifiers, used by Alembic.
revision = 'dd48947ccf75'
down_revision = 'e2cfd701b7ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publish', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conference_schedules', schema=None) as batch_op:
        batch_op.drop_column('publish')

    ### end Alembic commands ###
