"""add conference requester info

Revision ID: dde53052da30
Revises: 8dfaef9946ac
Create Date: 2018-04-12 13:01:23.224915

"""

# revision identifiers, used by Alembic.
revision = 'dde53052da30'
down_revision = '8dfaef9946ac'

from alembic import op
import sqlalchemy as sa
import app


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_info', app.utils.customDataType.NestedMutableJson(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('requester_info')

    ### end Alembic commands ###
