"""add email content in invitation

Revision ID: eaea5a74a92d
Revises: 00ceb8a6d037
Create Date: 2017-02-04 09:51:09.211737

"""

# revision identifiers, used by Alembic.
revision = 'eaea5a74a92d'
down_revision = '00ceb8a6d037'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_content', JsonObject, nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_column('email_content')

    ### end Alembic commands ###
