"""add custom question in submission

Revision ID: eef2781c83d3
Revises: 75b82a05837e
Create Date: 2017-09-13 13:51:10.178315

"""

# revision identifiers, used by Alembic.
revision = 'eef2781c83d3'
down_revision = '75b82a05837e'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_questions', JsonObject, nullable=True))

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_question_answer', JsonObject, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_column('custom_question_answer')

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.drop_column('submission_questions')

    ### end Alembic commands ###
