"""update payout

Revision ID: f02204821e8d
Revises: 2331b031f196
Create Date: 2017-07-18 21:06:38.118845

"""

# revision identifiers, used by Alembic.
revision = 'f02204821e8d'
down_revision = '2331b031f196'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.alter_column('bank_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('note')

    ### end Alembic commands ###
