"""remove session related table

Revision ID: f56664fc32ae
Revises: f02204821e8d
Create Date: 2017-07-19 20:34:00.665811

"""

# revision identifiers, used by Alembic.
revision = 'f56664fc32ae'
down_revision = 'f02204821e8d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussant_session')
    op.drop_table('paper_session')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_session',
    sa.Column('paper_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], [u'papers.id'], ),
    sa.ForeignKeyConstraint(['session_id'], [u'sessions.id'], )
    )
    op.create_table('discussant_session',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], [u'sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], )
    )
    ### end Alembic commands ###
