"""convert types

Revision ID: fc3420d65a2d
Revises: 3b20d207b79a
Create Date: 2016-11-01 22:52:26.123207

"""

# revision identifiers, used by Alembic.
revision = 'fc3420d65a2d'
down_revision = '3b20d207b79a'

from alembic import op
import sqlalchemy as sa
from app.utils.customDataType import NestedMutableJson as JsonObject


def upgrade():
    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.alter_column('review_questions',
               existing_type=sa.BLOB(),
               type_=JsonObject,
               existing_nullable=True)

    with op.batch_alter_table('form_configuration', schema=None) as batch_op:
        batch_op.alter_column('common_questions',
               existing_type=sa.BLOB(),
               type_=JsonObject,
               existing_nullable=True)
        batch_op.alter_column('configuration',
               existing_type=sa.BLOB(),
               type_=JsonObject,
               existing_nullable=True)

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.alter_column('private_question',
               existing_type=sa.BLOB(),
               type_=JsonObject,
               existing_nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('custom_question_answer',
               existing_type=sa.BLOB(),
               type_=JsonObject,
               existing_nullable=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('custom_question_answer',
               existing_type=JsonObject,
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.alter_column('private_question',
               existing_type=JsonObject,
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('form_configuration', schema=None) as batch_op:
        batch_op.alter_column('configuration',
               existing_type=JsonObject,
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('common_questions',
               existing_type=JsonObject,
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('conferences', schema=None) as batch_op:
        batch_op.alter_column('review_questions',
               existing_type=JsonObject,
               type_=sa.BLOB(),
               existing_nullable=True)


    ### end Alembic commands ###
